---
version: "3.4"

services:
  db:
    image: "postgres:13"
    ports: []
    #  - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-poieticgen}"
      POSTGRES_USER: "${POSTGRES_USER:-poieticgen}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-poieticgen}"
    networks:
      - poieticgen_net
    volumes:
      - poieticgen_db_data:/var/lib/postgresql/data
  
  app:
    build: .
    image: poieticgen:latest
    ports:
      - "127.0.0.1:${POIETIC_PORT}:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: "${POSTGRES_DB:-poieticgen}"
      POSTGRES_USER: "${POSTGRES_USER:-poieticgen}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-poieticgen}"

    networks:
      - poieticgen_net
  
volumes:
  poieticgen_db_data:

networks: 
  poieticgen_net:


