poieticdb:
  image: "postgres:9.5.3"
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=poieticgen
    - POSTGRES_USER=poieticgen
    - POSTGRES_PASSWORD=poieticgen

poieticapp:
  build: .
  links:
    - "poieticdb:db"
  ports:
    - "8000:8000"
  environment:
    - MYSQL_USER=poietic
    - MYSQL_PASSWORD=poieticgen

# poieticphpadm:
#   image: "phpmyadmin/phpmyadmin"
#   links:
#     - "poieticdb:db"
#   ports:
#     - "8002:80"
#   environment:
#     - MYSQL_USERNAME=root
#     - MYSQL_PASSWORD=poieticgen
