--- 
pid: tmp/pids/thin.pid
address: 0.0.0.0
wait: 30
timeout: 30
port: 9393
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
daemonize: true
#socket: /var/tmp/poieticgen.sock
#chdir: /home/opt/data/src/_Gnuside/poietic-generator-reloaded
